name: AWS Configure

on:
    push:
        branches:
            - main

jobs:
    aws:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: 'us-east-1'
            
            - name: SSH into EC2 Instance
              uses: jimmyptl-jer/Blog-Application@main
              with:
                host: ${{secrets.AWS_EC2_HOST}}
                username: ${{secrets.AWS_EC2_USERNAME}}
                key:  ${{secrets.AWS_EC2_SSH_KEY}}