name: AWS Configure

on:
  push:
    branches:
      - main

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: 'us-east-1'

      - name: SSH into EC2 Instance
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{secrets.AWS_EC2_HOST}}
          REMOTE_USER: ${{secrets.AWS_EC2_USERNAME}}
          SSH_PRIVATE_KEY:  ${{secrets.AWS_EC2_SSH_KEY}}
        script:
          #!/bin/bash

          # Install Docker
          sudo apt update
          sudo apt install -y docker.io

          # Start Docker service
          sudo systemctl start docker

          # Enable Docker service to start on boot
          sudo systemctl enable docker

          # Add current user to the docker group to run Docker commands without sudo
          sudo usermod -aG docker $USER

          # Restart Docker service to apply changes
          sudo systemctl restart docker
