name: AWS Configure

on:
  push:
    branches:
      - main

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: 'us-east-1'

      - name: SSH into EC2 Instance
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{secrets.AWS_EC2_HOST}}
          REMOTE_USER: ${{secrets.AWS_EC2_USERNAME}}
          SSH_PRIVATE_KEY:  ${{secrets.AWS_EC2_SSH_KEY}}
        
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/blog-application:client
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/blog-application:api
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker run -d -p 80:80 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/blog-application:client
            sudo docker run -d -p 3000:3000 --name my-node-app-api ${{ secrets.DOCKER_USERNAME }}/blog-application:api