name: AWS Configure

on:
  push:
    branches:
      - main

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: 'us-east-1'

      - name: SSH into EC2 Instance
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{secrets.AWS_EC2_HOST}}
          REMOTE_USER: ${{secrets.AWS_EC2_USERNAME}}
          SSH_PRIVATE_KEY:  ${{secrets.AWS_EC2_SSH_KEY}}
      
      - name: Install Docker and Configure
        run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt update
            sudo apt install docker.io -y
            sudo snap install docker
            sudo systemctl status docker
            docker --version
            docker